### ISSUE TITLE
Adjust phone prefix to start with 954 on tel field

### ISSUE THREAD

**Issue by jferragut** [jferragut/alkemy#47]

**Comment by cxjay26** [comment]
@jferragut I cannot see where 954 is listed as default area code for USA.

**Comment by jferragut** [comment]
![Screenshot_20191017-085215_Chrome](https://user-images.githubusercontent.com/31458614/67010377-83112400-f0bb-11e9-87df-2f47a26b4029.jpg)

**Comment by jferragut** [comment]
@cxjay26 that's a SS from my phone of the netlify preview. It's on the form that's located on the Responsive web design page

**Comment by cxjay26** [comment]
Got it, thanks.
