### ISSUE TITLE
Blog Card on Hompage (Title not same size)

### ISSUE THREAD

**Issue by jferragut** [jferragut/alkemy#54]
@cxjay26 can you take a look at this? 

Also, in the screenshot, it looks like the title section for the first blog card is larger than the rest. Please take a look into that. It's probably due to the truncation that is going on with the first card. if it's a CSS truncation, it may be detecting the full text size and making the region that big.

_Originally posted by @jferragut in https://github.com/jferragut/alkemy/issues/50#issuecomment-541447165_

**Comment by cxjay26** [comment]
Created PR that fixes this issue.

**Comment by jferragut** [comment]
PR passed and merged. Closing issue as resolved.
